import type { StartOptions } from "@glowhop/core-tour";

export const LAB_CONFIG = {
  workflow: {
    name: "api-lab",
    appendedName: "api-lab-appended",
    options: {
      cancellable: true,
      animated: true,
      overlay: {
        animated: true,
        animation: { duration: 260, easing: "ease-out" },
        color: "#151126",
        opacity: 0.68,
        padding: 12,
        radius: 14,
      },
      popover: {
        animated: true,
        animation: { duration: 220, easing: "ease-out" },
        placementTryOrder: ["bottom", "right", "top", "left"],
        arrow: {
          color: "#ffffff",
          size: 12,
          borderWidth: 1,
          borderRadius: 3,
          edgePadding: 18,
        },
        disableAutoFocus: false,
        gap: 14,
        keyboardShortcuts: {
          previous: ["ArrowLeft"],
          advance: ["Enter", "ArrowRight"],
          cancel: ["Escape"],
        },
      },
      indicator: {
        animated: true,
        animation: { duration: 220, easing: "ease-in-out" },
        disabled: false,
        gap: 12,
        placementTryOrder: ["right", "bottom", "left", "top"],
      },
      scroll: { behavior: "smooth", block: "center", inline: "nearest" },
      behavior: { missingTargetStrategy: "error", targetTimeout: 3000 },
    } satisfies StartOptions,
  },
  selectors: {
    start: "#api-lab-start",
    focusInput: "#api-lab-focus-input",
    revealButton: "#api-lab-reveal-button",
    revealed: "#api-lab-revealed",
    condition: "#api-lab-condition",
    actions: "#api-lab-actions",
    eventField: "#api-lab-event-field",
    clickAdvance: "#api-lab-click-advance",
    return: "#api-lab-return",
    previous: "#api-lab-previous",
    autoAdvance: "#api-lab-auto-advance",
    customEvent: "#api-lab-custom-event",
  },
  timing: {
    conditionDelay: 650,
    focusWait: 80,
    resolverWait: 5000,
    conditionAdvanceWait: 500,
    previousWait: 650,
    autoAdvanceWait: 650,
    pollingInterval: 25,
    elementPollingInterval: 20,
    targetTimeout: 10_000,
  },
  event: {
    completion: "api-lab:complete",
  },
  copy: {
    heading: "Builder API Lab",
    description: "Un parcours exécutable couvrant chaque API du builder Glow Tour.",
    targetsHeading: "Cibles du parcours",
    targetsSummary: "12 étapes · 17 méthodes",
    intro: "Le workflow démarre avec ses options globales et une cible par sélecteur CSS.",
    focus: "La cible est un HTMLElement transmis directement. Le champ reçoit le focus.",
    focused: "Focus appliqué. Cette phrase a été injectée via context.props.",
    reveal: "Le builder clique la cible, puis attend que l’interface rende le résultat.",
    resolver: "Cette cible est résolue par une fonction asynchrone après une pause déclarative.",
    condition: "Une condition applicative devient vraie, puis l’étape avance automatiquement.",
    actions:
      "La première action continue la chaîne. La seconde l’arrête avant l’action sentinelle.",
    eventField: "Survolez le champ ou appuyez sur une touche, puis continuez.",
    clickAdvance: "Le bouton Suivant est masqué. Cliquez directement sur la cible pour avancer.",
    automaticReturn:
      "Continuez. Cette étape saura vous renvoyer automatiquement après la démonstration suivante.",
    previous: "Premier passage : retour automatique. Second passage : la garde stoppe la boucle.",
    autoAdvance: "La navigation finale est automatique et le footer est masqué.",
    appended:
      "Cette étape vient d’un autre workflow. Déclenchez l’événement personnalisé pour finir.",
  },
} as const;
